import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

const harmattan = localfont ({
  src:[{
    path:"../user/font/Harmattan-Bold.ttf",
    weight:"1000",
    
  }],
  variable: "--font-harmattan",
 
})
export const metadata: Metadata = {
  title: "Ebasa User",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={harmattan.className}>
        
          {children}</body>
    </html>
  );
}
